from pathlib import Path
import re

path = Path("index.html")
src = path.read_text(encoding="utf-8")

videos = re.findall(r'<video[^>]*?src="([^"]+)"', src, flags=re.I)
images = re.findall(r'<img[^>]*?src="([^"]+)"', src, flags=re.I)

if len(videos) < 3 or len(images) < 2:
    raise SystemExit("Nao encontrei as 3 midias de video e 2 fotos no index.html")

template = r"""<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#063f31">
<meta name="apple-mobile-web-app-capable" content="yes">
<title>Nosso primeiro rolê de skate</title>
<style>
:root{--emerald-950:#032d23;--emerald-900:#053f31;--emerald-800:#075640;--emerald-700:#0a7152;--emerald-500:#24a678;--cream:#f6f3e8;--ink:#123127;--white:#fbfffc;--line:rgba(255,255,255,.14);--pink:#ef6f9c;--pink-dark:#d65082;--shadow:0 28px 70px rgba(0,24,17,.28)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;min-height:100vh;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:var(--white);background:radial-gradient(1200px 700px at 8% -10%,rgba(54,190,139,.20),transparent 62%),radial-gradient(900px 650px at 110% 25%,rgba(142,220,184,.12),transparent 58%),linear-gradient(145deg,var(--emerald-950),var(--emerald-900) 42%,#064b38 70%,var(--emerald-800));overflow-x:hidden}body::before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.46;background-image:repeating-radial-gradient(circle at 0 0,rgba(255,255,255,.026) 0 1px,transparent 1px 4px),repeating-linear-gradient(115deg,rgba(255,255,255,.018) 0 1px,transparent 1px 7px);mix-blend-mode:soft-light;z-index:0}body::after{content:"";position:fixed;inset:-25%;pointer-events:none;z-index:0;background:radial-gradient(circle at 38% 20%,transparent 0 26%,rgba(0,0,0,.05) 48%,rgba(0,0,0,.16) 80%)}button{font:inherit}
#gate{position:fixed;inset:0;z-index:50;display:grid;place-items:center;padding:24px;background:radial-gradient(700px 500px at 50% 35%,rgba(41,177,128,.22),transparent 68%),linear-gradient(150deg,#032b21,#063f31 58%,#07523c);transition:opacity .55s ease,visibility .55s ease}#gate.leaving{opacity:0;visibility:hidden}.gate-card{width:min(460px,100%);padding:34px 26px 28px;border:1px solid rgba(255,255,255,.14);border-radius:34px;background:linear-gradient(180deg,rgba(255,255,255,.10),rgba(255,255,255,.055));box-shadow:0 34px 90px rgba(0,0,0,.28);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);text-align:center}.eyebrow{margin:0 0 11px;font-size:.73rem;font-weight:800;letter-spacing:.18em;text-transform:uppercase;color:rgba(255,255,255,.62)}.gate-card h1{margin:0;font-size:clamp(2.1rem,9vw,3.5rem);line-height:.98;letter-spacing:-.045em}.gate-copy{max-width:31ch;margin:16px auto 27px;font-size:1rem;line-height:1.55;color:rgba(255,255,255,.78)}#enter{width:100%;padding:14px 0 10px;border:0;background:transparent;color:inherit;cursor:pointer;-webkit-tap-highlight-color:transparent}.fingerboard{position:relative;width:min(300px,78vw);height:112px;margin:0 auto;perspective:900px}.deck{position:absolute;inset:13px 0 22px;display:grid;place-items:center;border-radius:48% 48% 44% 44% / 26% 26% 74% 74%;background:radial-gradient(circle at 19% 34%,rgba(255,255,255,.28) 0 2px,transparent 2.5px),radial-gradient(circle at 81% 34%,rgba(255,255,255,.28) 0 2px,transparent 2.5px),linear-gradient(140deg,#ff8db7,var(--pink) 52%,var(--pink-dark));box-shadow:inset 0 1px 0 rgba(255,255,255,.34),inset 0 -10px 24px rgba(112,24,58,.18),0 18px 32px rgba(0,0,0,.24);color:#fff;transform-origin:center;transition:transform .85s cubic-bezier(.2,.8,.2,1),filter .4s ease}.deck::after{content:"";position:absolute;inset:8px 18px;border:1px solid rgba(255,255,255,.20);border-radius:999px}.deck-label{position:relative;z-index:1;display:flex;gap:10px;align-items:center;padding:9px 15px;border-radius:999px;background:rgba(4,58,43,.86);box-shadow:0 8px 18px rgba(0,0,0,.16);font-size:.92rem;font-weight:800;letter-spacing:.02em}.wheel{position:absolute;bottom:5px;width:27px;height:27px;border-radius:50%;background:#ece9df;box-shadow:inset 0 0 0 5px #1b2b26,0 8px 12px rgba(0,0,0,.22)}.w1{left:55px}.w2{left:95px}.w3{right:95px}.w4{right:55px}.fingerboard.flip .deck{transform:rotateY(360deg) rotateZ(-12deg) translateY(-6px);filter:saturate(1.08)}.fingerboard.flip .wheel{animation:wheelhop .85s ease}@keyframes wheelhop{50%{transform:translateY(-7px)}}.tapline{margin:4px 0 0;font-size:.84rem;color:rgba(255,255,255,.56)}
.page{position:relative;z-index:1;width:min(1120px,calc(100% - 28px));margin:0 auto;padding:18px 0 48px;opacity:0;transform:translateY(14px);transition:opacity .65s ease .1s,transform .65s ease .1s}.page.visible{opacity:1;transform:none}.topbar{display:flex;align-items:center;justify-content:space-between;min-height:62px;padding:0 4px;color:rgba(255,255,255,.64);font-size:.74rem;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.topbar .dot{width:7px;height:7px;border-radius:50%;background:var(--pink);box-shadow:0 0 0 5px rgba(239,111,156,.12)}
.hero{position:relative;overflow:hidden;display:grid;grid-template-columns:minmax(0,1.4fr) minmax(210px,.6fr);gap:28px;align-items:end;min-height:360px;padding:clamp(28px,5vw,58px);border:1px solid var(--line);border-radius:36px;background:radial-gradient(500px 280px at 95% 10%,rgba(239,111,156,.16),transparent 72%),linear-gradient(145deg,rgba(255,255,255,.13),rgba(255,255,255,.055));box-shadow:var(--shadow);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px)}.hero::before{content:"";position:absolute;width:360px;height:360px;right:-105px;top:-110px;border:1px solid rgba(255,255,255,.10);border-radius:50%;box-shadow:0 0 0 42px rgba(255,255,255,.018),0 0 0 84px rgba(255,255,255,.012)}.memory-id{display:inline-flex;align-items:center;gap:9px;margin-bottom:16px;padding:8px 12px;border-radius:999px;background:rgba(255,255,255,.10);color:rgba(255,255,255,.75);font-size:.72rem;font-weight:850;letter-spacing:.13em;text-transform:uppercase}.memory-id::before{content:"";width:7px;height:7px;border-radius:50%;background:var(--pink)}.hero h1{margin:0;max-width:11ch;font-size:clamp(3.2rem,8vw,6.8rem);line-height:.86;letter-spacing:-.065em}.hero p{margin:22px 0 0;max-width:52ch;color:rgba(255,255,255,.74);line-height:1.65;font-size:1.03rem}.hero-aside{position:relative;z-index:1;align-self:stretch;display:flex;flex-direction:column;justify-content:flex-end;padding-left:24px;border-left:1px solid rgba(255,255,255,.13)}.hero-aside .big{font-size:3.2rem;line-height:1;margin-bottom:16px}.hero-aside strong{font-size:1.05rem;line-height:1.25}.hero-aside span{margin-top:8px;color:rgba(255,255,255,.58);line-height:1.45;font-size:.9rem}
.section{margin-top:22px;padding:clamp(22px,4vw,38px);border:1px solid var(--line);border-radius:32px;background:linear-gradient(155deg,rgba(255,255,255,.09),rgba(255,255,255,.045));box-shadow:0 22px 56px rgba(0,24,17,.17);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px)}.section-head{display:flex;gap:18px;align-items:flex-start;justify-content:space-between;margin-bottom:22px}.section-kicker{margin:0 0 7px;color:rgba(255,255,255,.48);font-size:.71rem;font-weight:850;letter-spacing:.16em;text-transform:uppercase}.section h2{margin:0;font-size:clamp(1.9rem,4vw,3rem);line-height:1;letter-spacing:-.035em}.section-desc{max-width:34ch;margin:3px 0 0;color:rgba(255,255,255,.58);line-height:1.55;font-size:.92rem}
.video-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.media-card{position:relative;overflow:hidden;margin:0;border-radius:24px;background:#031e17;border:1px solid rgba(255,255,255,.11);box-shadow:0 18px 36px rgba(0,0,0,.18)}.media-card video{display:block;width:100%;aspect-ratio:9/16;object-fit:cover;background:#02140f}.clip-num{position:absolute;top:12px;left:12px;z-index:2;display:grid;place-items:center;width:35px;height:35px;border-radius:12px;background:rgba(2,35,26,.78);border:1px solid rgba(255,255,255,.13);backdrop-filter:blur(9px);font-size:.73rem;font-weight:900;letter-spacing:.08em;pointer-events:none}.media-card::after{content:"";position:absolute;inset:0;pointer-events:none;box-shadow:inset 0 -70px 70px -70px rgba(0,0,0,.78)}
.photo-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.photo{position:relative;overflow:hidden;border:0;padding:0;border-radius:25px;background:transparent;cursor:zoom-in;box-shadow:0 18px 38px rgba(0,0,0,.18);-webkit-tap-highlight-color:transparent}.photo img{display:block;width:100%;aspect-ratio:3/4;object-fit:cover;transition:transform .5s ease,filter .5s ease}.photo:hover img{transform:scale(1.018);filter:saturate(1.04)}.photo::after{content:"ver foto";position:absolute;right:13px;bottom:13px;padding:8px 11px;border-radius:999px;background:rgba(2,35,26,.73);border:1px solid rgba(255,255,255,.14);color:white;font-size:.7rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase;backdrop-filter:blur(8px)}
.quote{margin-top:22px;padding:clamp(32px,7vw,72px);border-radius:34px;background:var(--cream);color:var(--ink);box-shadow:0 26px 60px rgba(0,24,17,.20);position:relative;overflow:hidden}.quote::before{content:"“";position:absolute;top:-38px;left:18px;font-family:Georgia,serif;font-size:13rem;line-height:1;color:rgba(9,96,70,.08)}.quote p{position:relative;z-index:1;margin:0;max-width:20ch;font-family:Georgia,"Times New Roman",serif;font-size:clamp(2rem,5vw,4.4rem);line-height:1.08;letter-spacing:-.035em}.quote .second{color:#0b6a4d}.quote small{position:relative;z-index:1;display:block;margin-top:24px;color:rgba(18,49,39,.52);font-size:.72rem;font-weight:850;letter-spacing:.15em;text-transform:uppercase}.footer{padding:24px 6px 10px;display:flex;align-items:center;justify-content:space-between;color:rgba(255,255,255,.42);font-size:.73rem;letter-spacing:.12em;text-transform:uppercase}.footer b{color:var(--pink);font-size:1rem}
#lightbox{position:fixed;inset:0;z-index:80;display:none;place-items:center;padding:18px;background:rgba(1,22,16,.91);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px)}#lightbox.open{display:grid}#lightbox img{max-width:min(900px,96vw);max-height:88vh;border-radius:22px;box-shadow:0 30px 100px rgba(0,0,0,.42)}#lightbox button{position:absolute;top:max(18px,env(safe-area-inset-top));right:18px;width:44px;height:44px;border:1px solid rgba(255,255,255,.16);border-radius:50%;background:rgba(255,255,255,.09);color:white;font-size:1.45rem;cursor:pointer}
@media(max-width:760px){.page{width:min(100% - 20px,1120px);padding-top:8px}.topbar{min-height:52px;padding:0 4px}.hero{grid-template-columns:1fr;min-height:0;padding:30px 24px;border-radius:30px}.hero h1{font-size:clamp(3.3rem,17vw,5rem);max-width:7.5ch}.hero-aside{min-height:115px;padding:20px 0 0;border-left:0;border-top:1px solid rgba(255,255,255,.13)}.hero-aside .big{font-size:2.4rem;margin-bottom:10px}.section{padding:23px 18px;border-radius:28px}.section-head{display:block}.section-desc{margin-top:10px}.video-grid{display:grid;grid-auto-flow:column;grid-auto-columns:minmax(74vw,1fr);grid-template-columns:none;overflow-x:auto;overscroll-behavior-inline:contain;scroll-snap-type:x mandatory;scrollbar-width:none;margin-right:-18px;padding-right:18px}.video-grid::-webkit-scrollbar{display:none}.media-card{scroll-snap-align:start;border-radius:22px}.photo-grid{gap:10px}.photo{border-radius:20px}.quote{padding:40px 26px;border-radius:28px}.quote p{font-size:clamp(2rem,10vw,3.2rem)}.footer{padding-bottom:calc(10px + env(safe-area-inset-bottom))}}
</style>
</head>
<body>
<section id="gate"><div class="gate-card"><p class="eyebrow">uma lembrança nossa</p><h1>Tem uma coisa<br>guardada aqui.</h1><p class="gate-copy">Toca no skate pra abrir um pedacinho do nosso primeiro rolê juntos.</p><button id="enter" aria-label="Abrir a lembrança"><div class="fingerboard" id="fingerboard"><div class="deck"><span class="deck-label">🛹 &nbsp; entrar</span></div><span class="wheel w1"></span><span class="wheel w2"></span><span class="wheel w3"></span><span class="wheel w4"></span></div></button><p class="tapline">toca uma vez</p></div></section>
<div class="page" id="page"><div class="topbar"><span>memória 001</span><span class="dot"></span><span>nosso rolê</span></div><header class="hero"><div><span class="memory-id">primeiro rolê juntos</span><h1>Nosso primeiro rolê de skate</h1><p>Guardei aqui alguns pedacinhos daquele dia — uma tarde simples que virou uma lembrança especial pra mim.</p></div><aside class="hero-aside"><div class="big">🛹</div><strong>Um pedacinho daquele dia, guardado dentro de um skate.</strong><span>Porque algumas lembranças merecem um lugar só delas.</span></aside></header>
<section class="section"><div class="section-head"><div><p class="section-kicker">01 / vídeos</p><h2>Um pouco daquele dia</h2></div><p class="section-desc">Toca pra assistir aqui mesmo. Se quiser, o próprio player também abre em tela cheia.</p></div><div class="video-grid"><figure class="media-card"><span class="clip-num">01</span><video controls playsinline preload="metadata" src="__V1__"></video></figure><figure class="media-card"><span class="clip-num">02</span><video controls playsinline preload="metadata" src="__V2__"></video></figure><figure class="media-card"><span class="clip-num">03</span><video controls playsinline preload="metadata" src="__V3__"></video></figure></div></section>
<section class="section"><div class="section-head"><div><p class="section-kicker">02 / fotos</p><h2>Duas daquele fim de tarde</h2></div><p class="section-desc">As duas fotos que ficaram daquele dia. Toca em qualquer uma pra abrir maior.</p></div><div class="photo-grid"><button class="photo" data-full="__I1__" aria-label="Abrir primeira foto"><img src="__I1__" alt="Uma foto nossa naquele dia"></button><button class="photo" data-full="__I2__" aria-label="Abrir segunda foto"><img src="__I2__" alt="Outra foto nossa naquele dia"></button></div></section>
<section class="quote"><p>Cada momento contigo <span class="second">se vuelve más especial.</span><br>Y ojalá todavía nos queden muchos por compartir.</p><small>pra guardar — e, quem sabe, continuar</small></section><footer class="footer"><span>uma lembrança nossa</span><b>♥</b></footer></div>
<div id="lightbox" role="dialog" aria-modal="true" aria-label="Foto ampliada"><button id="closeLightbox" aria-label="Fechar">×</button><img id="lightboxImage" alt=""></div>
<script>
const gate=document.getElementById('gate'),enter=document.getElementById('enter'),fingerboard=document.getElementById('fingerboard'),page=document.getElementById('page');enter.addEventListener('click',()=>{fingerboard.classList.add('flip');setTimeout(()=>{gate.classList.add('leaving');page.classList.add('visible');window.scrollTo({top:0,behavior:'auto'})},620)},{once:true});
const lightbox=document.getElementById('lightbox'),lightboxImage=document.getElementById('lightboxImage');document.querySelectorAll('.photo').forEach(btn=>btn.addEventListener('click',()=>{lightboxImage.src=btn.dataset.full;lightbox.classList.add('open');document.body.style.overflow='hidden'}));function closeLightbox(){lightbox.classList.remove('open');lightboxImage.src='';document.body.style.overflow=''}document.getElementById('closeLightbox').addEventListener('click',closeLightbox);lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLightbox()});document.querySelectorAll('video').forEach(v=>v.addEventListener('play',()=>document.querySelectorAll('video').forEach(o=>{if(o!==v)o.pause()})));
</script>
</body></html>
"""

replacements = {
    "__V1__": videos[0],
    "__V2__": videos[1],
    "__V3__": videos[2],
    "__I1__": images[0],
    "__I2__": images[1],
}

for key, value in replacements.items():
    template = template.replace(key, value)

path.write_text(template, encoding="utf-8")
print("Pagina final gerada com sucesso.")
